### ISSUE TITLE
How to match lotte json file to each specific fragment

### ISSUE THREAD

**Issue by htooaunghlaing** [novoda/spritz#5]
If I have three onboarding slides,how to match 3 lotte animation json file to each fragment, Then, I found spritz-pager.json and combined all animation in one file and load only that file to lotte animation view. So, I would like to know how to create spritz-pager.json file.

**Comment by blundell** [comment]
@frapontillo any help here pls?

**Comment by juankysoriano** [comment]
Closing as the repository is no longer under maintenance and it's about to be archived
